baseurl = "https://a9ueduct.github.io/"
languageCode = "en-us"
title = "Aqueduct"
theme = "blank"

googleAnalytics = ""

[params]
    description = "Tokyo based visual performance unit"
    author = "Aqueduct"

